// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/comments" | "/admin/contributions" | "/admin/marketing" | "/admin/orders" | "/admin/ouvrages" | "/admin/statistics" | "/admin/users" | "/commande/annulee" | "/commande/echec" | "/commande/paiement/stripe" | "/commande/paypal/succes" | "/commande/succes" | "/connexion" | "/inscription" | "/ma-wishlist" | "/mes-achats" | "/mes-contributions" | "/mon-compte" | "/mot-de-passe-oublie" | "/ouvrages/[slug]" | "/panier" | "/reinitialiser-mot-de-passe"
type AppRouteHandlerRoutes = "/api/abandoned-cart" | "/api/admin/audit" | "/api/admin/books" | "/api/admin/bootstrap" | "/api/admin/comments" | "/api/admin/contributions" | "/api/admin/notifications/run" | "/api/admin/orders" | "/api/admin/promos" | "/api/admin/stats" | "/api/admin/users" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/reset-password" | "/api/auth/signup" | "/api/books" | "/api/books/[slug]" | "/api/comments" | "/api/comments/[id]/reply" | "/api/contributions" | "/api/contributions/stream" | "/api/me/cart" | "/api/me/cart/wishlist" | "/api/me/contributions" | "/api/me/orders" | "/api/me/orders/export" | "/api/me/password" | "/api/me/profile" | "/api/me/wishlist" | "/api/me/wishlist/share" | "/api/newsletter" | "/api/orders" | "/api/orders/[id]/invoice" | "/api/orders/cancel" | "/api/payments/paypal/complete" | "/api/payments/paypal/create-order" | "/api/payments/stripe/complete" | "/api/payments/stripe/embedded-session" | "/api/promo/validate" | "/api/wishlist/share/[token]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/comments": {}
  "/admin/contributions": {}
  "/admin/marketing": {}
  "/admin/orders": {}
  "/admin/ouvrages": {}
  "/admin/statistics": {}
  "/admin/users": {}
  "/api/abandoned-cart": {}
  "/api/admin/audit": {}
  "/api/admin/books": {}
  "/api/admin/bootstrap": {}
  "/api/admin/comments": {}
  "/api/admin/contributions": {}
  "/api/admin/notifications/run": {}
  "/api/admin/orders": {}
  "/api/admin/promos": {}
  "/api/admin/stats": {}
  "/api/admin/users": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/reset-password": {}
  "/api/auth/signup": {}
  "/api/books": {}
  "/api/books/[slug]": { "slug": string; }
  "/api/comments": {}
  "/api/comments/[id]/reply": { "id": string; }
  "/api/contributions": {}
  "/api/contributions/stream": {}
  "/api/me/cart": {}
  "/api/me/cart/wishlist": {}
  "/api/me/contributions": {}
  "/api/me/orders": {}
  "/api/me/orders/export": {}
  "/api/me/password": {}
  "/api/me/profile": {}
  "/api/me/wishlist": {}
  "/api/me/wishlist/share": {}
  "/api/newsletter": {}
  "/api/orders": {}
  "/api/orders/[id]/invoice": { "id": string; }
  "/api/orders/cancel": {}
  "/api/payments/paypal/complete": {}
  "/api/payments/paypal/create-order": {}
  "/api/payments/stripe/complete": {}
  "/api/payments/stripe/embedded-session": {}
  "/api/promo/validate": {}
  "/api/wishlist/share/[token]": { "token": string; }
  "/commande/annulee": {}
  "/commande/echec": {}
  "/commande/paiement/stripe": {}
  "/commande/paypal/succes": {}
  "/commande/succes": {}
  "/connexion": {}
  "/inscription": {}
  "/ma-wishlist": {}
  "/mes-achats": {}
  "/mes-contributions": {}
  "/mon-compte": {}
  "/mot-de-passe-oublie": {}
  "/ouvrages/[slug]": { "slug": string; }
  "/panier": {}
  "/reinitialiser-mot-de-passe": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
